language: node
node_js:
  - 12.7.0
jobs:
  fast_finish: true
script:
  - npm run build
env:
  global:
    - PUSHER_APP_KEY=154e65adf3fecc2c5e49
    - PUSHER_APP_CLUSTER=mt1
    - PUSHER_APP_ID=978203
    - secure: nVU2vBEG1oU/eYt/C65PpptCMTLezg8g9WMhxdkqhRIKf32HTiL8kSI5mzZMlQ2fLWnPYA2mG+OxlOtzyxBY/drJMYBPKtSwZCzFLgkYAsTJSAfKzHL2pEYrmKx7Y5AeL0xuFBQFzvaGXFkqAntMgsXEwlwmFoz/P/U+4VnCYu2fmrnlRl3MSdspv/l+kd2f7KC6w/3D7ndb2DeXgoGgG52GNFywERJeST/eLdGUOgTzYwSepS2Q4UeFjXlj4uMiuy/Jly1MExPS+4UGhmEI6czjJUBOCpJhooJVSg8lTVe+PX2L4fOZai4Xffh1R6NKEfU5lskMXieuRF8yZqvdywtWNEWiyfPUSyNg0N6YjEC8Z97h+FkQWHZQTo/DsVfRkOtENXcpMOY6zPJ8urBOT+qkD3NFL4FV2dhJjHnSwPvrWdjgM9H0wvTUiN+33zDYwQB9G/yD9yvTY0WLT4xaexCfh/LRRTgF2Rk6IpRbdRjIdu3ZHW+sacCATffbVBgW6100KNoUN3+zH056/fwcYmrjZysd++ofYF8OyLvjzi61ssrzLQG53jG3FHIll59wg32EwUvFcAUFLDUk2pPYEfJfYdahMtX5JF8gLjEje+CnZzb3chMda8hxo+dQe1ziQp26j55z7vnX3zZ5F0C7AC7kMDR6z3JCagn/eTE7+0w=
before_deploy:
  - git config --local user.name "xyclos"
  - git config --local user.email "jake@xyclos.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - npm pack poker-bot-$TRAVIS_TAG.tgz
deploy:
  provider: releases
  api_key:
    secure: QZZ0qy2eH7fUI+v0iPTART1A8eFkp3AXZGQZhGTmSmRx9G9bgAPA2zRl35iKhbMMKKhDy7JgrSC6R+Cjl2f/8GfRucKPpJ9nPTbMY8TRiTYEz0vUHBEtEtfa54qFqSXhfLwtcmLbcmcTobYQZT6C13XJhKujxu5Devv7dSYosX/wxa772VHJn6jY2SQHsvAt52GJQiYKj/8+GTZoPfi6k4DUMLkRoov0099JTJp+uxO25HL0eBRjzHiWni4l3xRwDW5FXaorVMCNDdxKtvFDJR68P8LlZiBVRYwQbubc/Hj/KQvU3BOSWiGyy9QbglbICRK/hYCZs9AtGVQRNxk4qKbLSouKeDDpI4700tzIm1u8VYNcrl42MRBfoh9oJAPKqYaHQjl2vQnlTjCyUk01zStqqgRBsNlVJgjiUBGHFkWhojVMK/Q0ppSMNiPbSOYPAaDwuzJp30+GNmYwY1MSraaGUCv7IesJBIf8QYfvyR/ZHPJCSOudYqfFhz+BG7McBU8vcYM/ex3XdwJguE0KOwuWbogv+ttUh/FRDmgZJ5KoDqhzL9OYjmLA3YrQuom/9yuCaKL2rjzHIF4ctNNQdx0jk39dcLOEQzbDFALrPnqHaFHNgmrEbOJFb8qT5lt8+vmxm+EhmGYhDzCwd8snbW/eyZjxORjj+ZBbH84cRC8=
  file: poker-bot-$TRAVIS_TAG.tgz
  on:
    repo: xyclos/poker-bot
